services:
  scarpetoss:
    container_name: scarpetoss
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    expose:
      - "7000"
    ports:
      - "7000:7000"
    restart : always
